[package]
name = "lazy_dict"
version = "0.1.0"
authors = ["planet"]

[dependencies]
# glutin = "0.18.0"
# android_glue = "*"
# piston_window = "*"
# allegro = {path="RustAllegro/allegro"}
# allegro_font = {path="RustAllegro/allegro_font"}
# allegro_ttf = {path="RustAllegro/allegro_ttf"}
png = "*"
log = "*"
lazy_static = "*"
jni = { version = "*", default-features = false }
jni-sys = { version = "*", default-features = false }
android_logger = "*"
android_support = "*"
zip = { version = "*", features = ["deflate-zlib"], default-features = false }
winit = "*"
android_injected_glue = "*"
android_glue = "*"
piston_window = "*"
[dependencies.pistoncore-glutin_window]
git = "https://github.com/PistonDevelopers/glutin_window"

[lib]
crate-type = ["dylib"]

[profile.release]
lto = true
#panic = 'abort'