[package]
name = "lazy_dict"
version = "0.1.0"
authors = ["planet"]

[dependencies]
# glutin = "0.18.0"
# android_glue = "*"
# piston_window = "*"
# allegro = {path="RustAllegro/allegro"}
# allegro_font = {path="RustAllegro/allegro_font"}
# allegro_ttf = {path="RustAllegro/allegro_ttf"}
png = "0.12.0"
log = "*"
lazy_static = "*"
jni = { version = "*", default-features = false }
jni-sys = { version = "*", default-features = false }
android_logger = "0.5"
android_support = "0.1.0"
zip = { version = "0.4", features = ["deflate-zlib"], default-features = false }

[lib]
crate-type = ["dylib"]

[profile.release]
lto = true
#panic = 'abort'