[package]
name = "demo"
version = "0.1.0"
authors = ["Jia Ye <planet0104@gmail.com>"]

[dependencies]
# serde_json = "1.0.32"
# bincode = "1.0.1"
jieba-rs = "0.2"
#image = "*"
#imageproc = "*"
#rand = "0.5.5"