[package]
name = "demo"
version = "0.1.0"
authors = ["Jia Ye <planet0104@gmail.com>"]

[dependencies]
serde_json = "1.0.32"
bincode = "1.0.1"
serde_derive = "1.0.80"
serde = "1.0.80"
hyper = "0.12.13"
futures = "*"
hyper-tls = "*"
tokio = "*"
#image = "*"
#imageproc = "*"
#rand = "0.5.5"