[package]
name = "lazy_dict"
version = "0.1.0"
authors = ["planet"]

[dependencies]
libc = "*"
log = "*"
lazy_static = "1.1.0"
jni = { version = "*", default-features = false }
android_logger = "*"
android_support = "*"
zip = { version = "*", features = ["deflate-zlib"], default-features = false }
bytes = "*"
sdl2 = "0.32.0-beta.2"
#image = "*"
glutin = "*"
egl = "*"
gfx_device_gl = "0.15.0"
gfx = "0.17.1"
piston2d-gfx_graphics = "0.52.0"
shader_version = "*"
piston2d-graphics = "*"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
#panic = 'abort'